version: "3.9"

networks:
    default:
        name: "ai-melodies-app"

services:
    app:
        container_name: ng-app
        image: "ttomasic/ai-melodies-app:latest"
        ports:
            - "4200:4200"
        environment:
            - PORT=4200
